name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Inputing "apple,banana,kiwi" test
      id: inputing-apple-banana-kiwi-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Inputing "apple,banana,kiwi" test
        setup-command: ''
        command: python3 reverse_capitalize/main.py
        input: apple,banana,kiwi
        expected-output: "^Kiwi\\nBanana\\nApple\\n?$"
        comparison-method: regex
        timeout: 10
        max-score: 2
    - name: inputting "orange,  mango , lychee" test
      id: inputting-orange-mango-lychee-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: inputting "orange,  mango , lychee" test
        setup-command: ''
        command: python3 reverse_capitalize/main.py
        input: orange,  mango , lychee
        expected-output: "^Lychee\\nMango\\nOrange\\n?$"
        comparison-method: regex
        timeout: 10
        max-score: 2
    - name: Inputting "Cherry,apple,Peach" test
      id: inputting-cherry-apple-peach-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Inputting "Cherry,apple,Peach" test
        setup-command: ''
        command: python3 reverse_capitalize/main.py
        input: Cherry,apple,Peach
        expected-output: "^Peach\\nApple\\nCherry\\n?$"
        comparison-method: regex
        timeout: 10
        max-score: 1
    - name: Inputting "dragonfruit" test
      id: inputting-dragonfruit-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Inputting "dragonfruit" test
        setup-command: ''
        command: python3 reverse_capitalize/main.py
        input: dragonfruit
        expected-output: "^Dragonfruit\\n?$"
        comparison-method: regex
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        INPUTING-APPLE-BANANA-KIWI-TEST_RESULTS: "${{steps.inputing-apple-banana-kiwi-test.outputs.result}}"
        INPUTTING-ORANGE-MANGO-LYCHEE-TEST_RESULTS: "${{steps.inputting-orange-mango-lychee-test.outputs.result}}"
        INPUTTING-CHERRY-APPLE-PEACH-TEST_RESULTS: "${{steps.inputting-cherry-apple-peach-test.outputs.result}}"
        INPUTTING-DRAGONFRUIT-TEST_RESULTS: "${{steps.inputting-dragonfruit-test.outputs.result}}"
      with:
        runners: inputing-apple-banana-kiwi-test,inputting-orange-mango-lychee-test,inputting-cherry-apple-peach-test,inputting-dragonfruit-test
